name: CI/CD pipeline

on:
  push:
    branches:
      - 'main'
      - '**'
  delete:
    branches:
      - '**'

env:
  TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
  PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  PYTHON_VERSION: '3.10'
  APPROVERS: caolan947

jobs:
  test:
    name: Running unit tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip

  build-n-publish-test:
    name: Build and publish to Test PyPI
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install build dependencies
      run: |
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ env.TEST_PYPI_API_TOKEN }}

  build-n-publish:
    name: Build and publish to PyPI
    if: startsWith(github.ref, 'refs/tags')
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: trstringer/manual-approval@v1
      timeout-minutes: 60
      with:
        secret: ${{ github.TOKEN }}
        issue-title: "Deploying to PyPi"
        issue-body: "Please approve or deny the deployment"
        approvers: ${{ env.APPROVERS }}
    - uses: actions/checkout@master
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install build dependencies
      run: |
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ env.PYPI_API_TOKEN }}